image: nfcore/gitpod:latest

tasks:
  - name: Update Nextflow
    command: nextflow self-update
  - name: Install Pixi
    command: |
      sudo chown gitpod -R /home/gitpod/
      curl -fsSL https://pixi.sh/install.sh | bash
      . /home/gitpod/.bashrc
      pixi global install multiqc jupyter -c conda-forge -c bioconda

vscode:
  extensions:
    - quarto.quarto
    - esbenp.prettier-vscode
    - nextflow.nextflow
