[project]
authors = ["Mahesh Binzer-Panchal <mahesh.binzer-panchal@nbis.se>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "nextflow-quarto-multiqc-demo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
nextflow = {cmd = "nextflow run $SCRIPT -resume", env = { SCRIPT = "main.nf" }}
quarto = "quarto render"

[dependencies]
quarto = ">=1.5.55,<2"
nextflow = ">=24.4.4,<25"
